# model settings
name: SSTReal_X4
model_type: EdmUNetRealModel
scale: 4
num_gpu: 40  # We used 40 A10 GPUs for training. 
manual_seed: 0
find_unused_parameters: False
use_amp: true
compile_network: True

# dataset and data loader settings
degradation:
  sf: 4
  # the first degradation process
  resize_prob: [0.2, 0.7, 0.1]  # up, down, keep
  resize_range: [0.15, 1.5]
  gaussian_noise_prob: 0.5
  noise_range: [1, 30]
  poisson_scale_range: [0.05, 3.0]
  gray_noise_prob: 0.4
  jpeg_range: [30, 95]

  # the second degradation process
  second_order_prob: 0.5
  second_blur_prob: 0.8
  resize_prob2: [0.3, 0.4, 0.3]  # up, down, keep
  resize_range2: [0.3, 1.2]
  gaussian_noise_prob2: 0.5
  noise_range2: [1, 25]
  poisson_scale_range2: [0.05, 2.5]
  gray_noise_prob2: 0.4
  jpeg_range2: [30, 95]

  gt_size: 512 
  resize_back: true
  use_sharp: False

datasets:
  train:
    name: DFLIP
    type: RealESRGANDataset
    dataroot_gt: /home2/prof/ro/dslisleedh/datasets/DFLIP.lmdb
    io_backend:
      type: lmdb
    blur_kernel_size: 21
    kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
    kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
    sinc_prob: 0.1
    blur_sigma: [0.2, 3.0]
    betag_range: [0.5, 4.0]
    betap_range: [1, 2.0]

    blur_kernel_size2: 15
    kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
    kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
    sinc_prob2: 0.1
    blur_sigma2: [0.2, 1.5]
    betag_range2: [0.5, 4.0]
    betap_range2: [1, 2.0]

    mean: 0.5
    std: 0.5

    final_sinc_prob: 0.8

    gt_size: 512
    use_hflip: True
    use_rot: False

    # data loader
    num_worker_per_gpu: 12
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: True
    persistent_workers: True

  val_1:
    name: RealSRSet
    type: SingleImageDataset
    dataroot_lq: /home2/prof/ro/dslisleedh/datasets/RealSRSet+5images
    mean: 0.5
    std: 0.5
    io_backend:
      type: disk

# network structures
network_g:
  type: EDMUNet
  img_resolution: 192
  img_channels: 3
  scale: 4
  sigma_data: 0.5
  sigma_min: 0
  use_skip: True
  sampling_ig_lambda: 1.0

  dim: 192
  intermediate_dim: 96
  emb_channels: 768
  noise_channels: 192
  num_blocks: 14
  fuse_lr_till: 6  
  ig_idx: 6       
  attn_type: RIB
  window_sizes: [16, 32, 64, 16, 32, 64]
  num_heads: [6, 6, 6, 6, 6, 6]
  ranks: [16, 16, 16, 32, 32, 32]
  rib_hidden_dim: 32
  rib_n_freqs: 10
  exp_ratio: 3
  gate_type: DWC
  drop_p: 0.05

# training settings
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999

  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: !!float 2e-4
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [400000]
    gamma: 0.5

  total_iter: 400000
  warmup_iter: 10000

  consistency_opt:
    loss_opt:
      l_opt1:
        type: lpips
        weight: 0.5

      l_opt2:
        type: charbonnier
        weight: 0.5

    sigma_min: 0
    sigma_max: 1
    noise_rho: 1
    res_rho: 1
    s0: 4
    s1: 3
    use_enc: true

# validation settings
val:
  val_freq: 10000
  save_img: True

  metrics:
    # psnr: # metric name, can be arbitrary
    #   type: calculate_psnr
    #   crop_border: 0
    #   test_y_channel: yes
    
    # ssim: # metric name, can be arbitrary
    #   type: calculate_ssim
    #   crop_border: 0
    #   test_y_channel: yes

    # lpips:
    #   type: calculate_lpips
    #   better: lower
      
    clipiqa:
      type: calculate_clipiqa
      better: higher
    
    musiq:
      type: calculate_musiq
      better: higher
    
    maniqa:
      type: calculate_maniqa
      better: higher
    
    niqe:
      type: calculate_niqe
      better: lower
    

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 10000
  use_tb_logger: false
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
